import shutil
#shutil.copyfileobj(open('/etc/passwd','rb'),open('/tmp/mima.txt','wb'))
#shutil.copyfile('/etc/passwd','/tmp/mima2.txt')
#shutil.copy('/etc/shadow','/tmp/')
#shutil.copy2('/tmp/shadow','/mnt')
#shutil.move('/tmp/mima2.txt','/mnt/tmp/')
#shutil.copytree('/etc/yum.repos.d','/mnt/myyum/')
#shutil.rmtree('/mnt/myyum')
#shutil.copymode('/etc/shadow','/mnt/tmp/mima2.txt')
#shutil.copystat('/etc/shadow','/mnt/tmp/mima2.txt')
#shutil.chown('/mnt/tmp/mima2.txt',user='wsw',group='wsw')